Read commited
skyrocknroll/janusgraph-foundationdb pull request #4
Opened 2019-12-26 21:25 UTC by hari-om-888

2019-12-26 21:31 UTC, hari-om-888 commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +        if(IsolationLevel.READ_COMMITTED_NO_WRITE.equals(isolationLevel)
https://apple.github.io/foundationdb/developer-guide.html#snapshot-reads
With snapshot reads, reads will see last successfully committed transaction version of the key. The key values may change after the read occurred.

2019-12-26 21:31 UTC, hari-om-888 commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +                ReadTransaction transaction  = getTransaction(this.isolationLevel, this.tx);
moving reads to another method to leverage snapshot reads.
https://apple.github.io/foundationdb/developer-guide.html#snapshot-reads

2019-12-26 21:31 UTC, hari-om-888 commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +                result = transaction.getRange(new Range(startKey, endKey), limit).asList().get();
same as above

2019-12-27 05:56 UTC, skyrocknroll requested changes

2019-12-27 05:56 UTC, skyrocknroll commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import com.apple.foundationdb.*;
Good to move away from wildcard imports

2019-12-27 06:44 UTC, hari-om-888 commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import com.apple.foundationdb.*;
For not conflicting imports, it doesn't matter. Also these days, intellij does the optimization of imports. this was done by intellij, auto format indents.

2019-12-27 06:55 UTC, skyrocknroll commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import com.apple.foundationdb.*;
I would still recommend using explicit import which will make the code more readable.  Once we start having multiple wildcard imports then the dance starts :) I would request to disable the IntelliJ feature which collapsed the explicit imports. Intellij is supposed to make the code more readable not the other way around :D

2019-12-27 11:39 UTC, hari-om-888 commented on src/main/java/com/experoinc/janusgraph/diskstorage/foundationdb/FoundationDBTx.java
> +import com.apple.foundationdb.*;
Code Readability is not affected by imports. It is pretty easy to track which dependency is used. Also if some imports collide, intellij will not collapse imports to *
Anyways, updated the pr to move away from collapsed imports.

2020-01-06 08:44 UTC, upaangsaxena approved these changes

2020-01-13 09:44 UTC, closed without merging